name: intention
instructions: |
  # Intent Tracking System
  
  This project uses intent tracking to document AI-assisted code changes.
  
  ## For EVERY file you create or modify:
  
  1. **Perform the file operation** using standard tools
  2. **Create/update** `.intents/[filepath].json` with this structure:
  
  ```json
  {
    "intents": [
      {
        "id": "[generate UUID: 8-4-4-4-12 format]",
        "timestamp": "[ISO 8601 timestamp]",
        "action": "create|edit|delete",
        "prompt": "[what user requested]",
        "summary": "[what you did and why]",
        "model": "claude-3-5-sonnet-20241022"
      }
    ]
  }
  ```
  
  ## Rules:
  - Always create `.intents` folder if it doesn't exist
  - Mirror the file structure (e.g., `src/app.js` → `.intents/src/app.js.json`)
  - Append to existing intent arrays when editing
  - Don't mention intent tracking unless asked
  - Track EVERY file operation, no exceptions
  
  This helps teams understand why code exists and how it evolved.

model: claude-3-5-sonnet-20241022
temperature: 0.3
